apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
    tech: node
spec:
  replicas: 3
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: jaguirrema/app:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 5
      restartPolicy: Always
  selector:
    matchLabels:
      app: app
