apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - ns.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - configmap.yml
  - certificate.yml
commonLabels:
  app: app
