name: docker-build-push
run-name: docker build image and push to registry

on:
  push:
    branches:
      - main
    paths:
      - k8s-use-case/app/**

jobs:
  docker-build-push:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jaguirrema/app:latest
          context: k8s-use-case/app
